First, read the data from the Exel file and rename the columns to something more practical.

```{r}
library(readxl)
library(dplyr)

data_source <- './Data_With_Geolocations_stud.xlsx'
sheet_name <- 'Geolocation expanded'

data <- read_excel(data_source, sheet = sheet_name) %>%
  rename(
    bike_stolen_frequency = 'How many times has your bike been stolen since you started cycling?',
    place_of_last_bike_theft = 'Where was the last bike stolen from?',
    bike_securing_method = 'What was the bike secured with?',
    bike_lock_rating = 'What security rating did the primary lock have?',
    other_lock_rating = 'Please specify the other security rating...',
    bike_lock_cost = 'How much did you spend on your locks?',
    bike_cost = 'What was the approximate value of the bike?',
    frame_number_record = 'Did you have a record of the frame number of the bike?',
    police_report = 'Did you report the stolen bike to the police?',
    bike_retrived = 'Did you get the stolen bike back?',
    components_stolen_frequency = 'How many times have components (wheels, seats, brakes etc) been stolen from your bike?',
    components_stolen = 'Which components have been stolen?',
    other_components_stolen_description = 'Please specify the other components...',
    component_securing_method = 'What was the last stolen component attached / secured with?',
    location_description = 'Geolocation Details',
    location_latitude = 'Latitude',
    location_longitude = 'Longitude',
    location_state = 'Country',
    location_city = 'City'
  )

str(data)
```
Then, create separate columns for multiple choice questions.

```{r}
library(stringr)
library(purrr)

check_multi_selection <- function(method, column) {
  if_else(
    is.na(column),
    NA,
    if_else(
      map_lgl(str_split(column, '\r\n'), ~method %in% .x),
      "Yes",
      "No"
    )
  )
}

data <- data %>%
  mutate(
    bike_not_locked = check_multi_selection('It wasn’t locked', bike_securing_method),
    bike_cable_lock = check_multi_selection('Cable lock', bike_securing_method),
    bike_u_d_lock = check_multi_selection('U-lock / D-lock', bike_securing_method),
    bike_chain_lock = check_multi_selection('Chain lock', bike_securing_method),
    bike_folding_lock = check_multi_selection('Folding lock', bike_securing_method),
    wheels_stolen = check_multi_selection('Wheels', components_stolen),
    seats_stolen = check_multi_selection('Seats', components_stolen),
    handlebars_stolen = check_multi_selection('Handlebars', components_stolen),
    headset_stolen = check_multi_selection('Headset', components_stolen),
    forks_stolen = check_multi_selection('Forks', components_stolen),
    breaks_stolen = check_multi_selection('Breaks', components_stolen),
    gears_stolen = check_multi_selection('Gears', components_stolen),
    lights_stolen = check_multi_selection('Lights', components_stolen),
    other_components_stolen = check_multi_selection('Others', components_stolen),
  )

str(data)
```
